### PR TITLE
Clarify reverse_each advice.

### PR DESCRIPTION
**Pull request by IronSavior**

### CODE REVIEW

**Comment by bbatsov** [comment]
@IronSavior ping

**Comment by IronSavior** [comment]
Sorry for the delay. I trimmed it down a bit.

**Comment by bbatsov** [comment]
Looks good. Just squash the two commits together.

**Comment by IronSavior** [comment]
And done.

**Comment by onebree** [comment]
@bbatsov Random question, how do you "squish commits together"? If it were me, I'd `reset --hard <commit>` and make all changes as one commit (if it were simple like this PR). But I notice that the date of commit for this PR is still in September

**Comment by bbatsov** [comment]
@onebree Like this http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by IronSavior** [comment]
@onebree When you squash via `git rebase -i`, some information related to the newer commit (like the time) is lost. However, a new commit is created when the pull request is merged (at least when merged via github's 1-click merge button). This new commit reflects the time of the merge itself.

**Comment by onebree** [comment]
Thank you, both. I am aware of pull request merges/commits. Thank you for the link on rebase. That is one part of git I do not understand but want to know more about. That site looks easy to chew, too! (Unlike the official docs)

**Pull request merged**
