### PR TITLE
correct code example of optional arguments

### PR DESCRIPTION
**Pull request by kangkyu**
This way it keeps the code give out the result in example, I guess

### CODE REVIEW

**Comment by mentero** [comment]
:+1: nice catch

**Comment by arbox** [comment]
I don't think this correction should be accepted since it breaks the compatibility with the previous bad example.

**Comment by mentero** [comment]
But the current one doesn't work. Output from the examples is just wrong.

**Comment by arbox** [comment]
I think we'd rather correct the output, but up to the editor :)

**Comment by onebree** [comment]
I can go either way with this PR. I see why have `c` and `d` the predefined arguments, but at the same time, I think it depends on how the variables are called. I like having the arguments in order as to how I call them, so if `a` is called first in the method AND is predefined, I will place it last `bcda` in the argument list.

**Comment by kangkyu** [comment]
Anyways it should be corrected. By the way how about options hash instead.

**Comment by bbatsov** [comment]
Let's correct the output.

**Comment by kangkyu** [comment]
Output has been corrected https://github.com/bbatsov/ruby-style-guide/commit/31b229bacb9e1bc510412ca7628e0b79eba2449e this pull request can be closed 😄

**Pull request closed without merging**
