### PR TITLE
add Egyptian arabic translation file

### PR DESCRIPTION
**Pull request by HassanTC**
I've just made a new translation by Egyptian-Arabic language

### CODE REVIEW

**Comment by M-Hamed** [comment]
Great Job

**Comment by Amrrbakry** [comment]
Great effort, Hassan!

**Comment by arbox** [comment]
I think it helps if the translations list is alphabetically ordered.

Anyway great job!

**Comment by HassanTC** [comment]
@arbox updated :+1:

**Comment by bbatsov** [comment]
Nice work! 👍

**Pull request merged**
