### PR TITLE
Minor formatting improvements

### PR DESCRIPTION
**Pull request by 0x01f7**

### CODE REVIEW

**Comment by 0x01f7** [comment]
Yes, I see “Programming Ruby”, "Programming Ruby 1.9", "Programming Ruby 1.9&2.0", etc. But is't better to keep a same name in one style guide? In [here](https://github.com/bbatsov/ruby-style-guide#the-ruby-style-guide), we use "Programming Ruby 1.9".

**Comment by bbatsov** [comment]
> Yes, I see “Programming Ruby”, "Programming Ruby 1.9", "Programming Ruby 1.9&2.0", etc. But is't better to keep a same name in one style guide? In here, we use "Programming Ruby 1.9".

Sure. Let's just use `Programming Ruby` everywhere.

**Comment by 0x01f7** [comment]
OK. I drop the old commit, and make a new one to keep the book name "Programming Ruby".

**Comment by 0x01f7** [comment]
Following your advice, I have changed the commit messages. :smiley:

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
