### PR TITLE
Corrected broken links.

### PR DESCRIPTION
**Pull request by arbox**

### CODE REVIEW

**Comment by bbatsov** [comment]
:+1: 10x

**Comment by onebree** [comment]
Thanks for that, @arbox -- I used `git rebase` for the first time and missed that change.

**Comment by arbox** [comment]
You are welcome, @onebree

**Comment by 0x01f7** [comment]
As far as I know, this PR did not fix the problem. You should use **pad-string-interpolation** rather than **string-interpolation**, since the href name **string-interpolation** had been already token by the 1st rule in section **Strings**.

```Markdown
## Strings

* <a name="string-interpolation"></a>
...
<sup>[[link](#string-interpolation)]</sup>

...

* <a name="pad-string-interpolation"></a>
...
<sup>[[link](#pad-string-interpolation)]</sup>
```

**Pull request merged**
