### PR TITLE
proposed memoizing style

### PR DESCRIPTION
**Pull request by ivar**
I've seen a few variable initialization styles and this is what we ended up standardizing on for my current team. I'm curious as to how the community at large feels about this particular approach. 

Regardless of what ends up being considered the correct style for perform initialization, it'd be good to get something like this in the Mr. Batsov's styleguide.

### CODE REVIEW

**Comment by 0x01f7** [comment]
You can't use `return` keyword or any instance variables unless in a method declaration. And can you explain why the first style is bad. Thanks.

**Comment by arr-dev** [comment]
I believe the accepted style for multi-line is:

```rb
@name ||= begin
  # compute
end
```

**Comment by WaKeMaTTa** [comment]
```ruby
return @name unless name.nil
```

**Comment by bbatsov** [comment]
@arr-dev is right.

**Pull request closed without merging**
