### PR TITLE
use private_class_method to make class methods private

### PR DESCRIPTION
**Pull request by akshaymohite**

### CODE REVIEW

**Comment by Lucasosf** [comment]
I think using private_class_method isn't clear enough such as the current way.

**Comment by freemanoid** [comment]
What about using `private_class_method` inline:
```ruby
class TestClass
  private_class_method def self.some_method
    # body omitted
  end
end
```

**Comment by philoserf** [comment]
I do not see the benefit. I found this quote in my search for 'prior art' on the question, "Makes existing class methods private." It struck a cord with me.

I believe the style marked 'bad' in this PR is the common case. If I need included code, I do not own to 'become' private i would use `private_class_method` to re-scope it.

**Comment by bbatsov** [comment]
> I believe the style marked 'bad' in this PR is the common case. If I need included code, I do not own to 'become' private i would use private_class_method to re-scope it.

The "common case" actually does nothing, but this is a logic error, not something that should be in a style guide.

**Comment by onebree** [comment]
Throughout our company's app, we include `private`, followed by methods for params, page name, and a couple other things... According to what @philoserf said, this means stating `private` does nothing to the methods that follow.

If so, then why include `private`? What _does_ it do?

**Comment by bbatsov** [comment]
`private` works on instance methods, but not on class methods.

**Comment by jaredbeck** [comment]
> `private` works on instance methods, but not on class methods.

This is a common mistake. As such, I would like some way to help my projects avoid this mistake.  Maybe it could be implemented in rubocop?

> .. this is a logic error, not something that should be in a style guide.

If applied consistently, that makes sense, even though [other popular style guides][1] do chose to cover logic errors.

[1]: https://github.com/airbnb/javascript

**Comment by bbatsov** [comment]
> This is a common mistake. As such, I would like some way to help my projects avoid this mistake. Maybe it could be implemented in rubocop?

RuboCop will warn you if you do something like this. :-)

**Comment by jaredbeck** [comment]
>> This is a common mistake. As such, I would like some way to help my projects avoid this mistake. Maybe it could be implemented in rubocop?
> 
> RuboCop will warn you if you do something like this. :-)

Thanks! I tried it out, but it doesn't catch all permutations of this mistake (https://github.com/bbatsov/rubocop/issues/2505)

**Pull request closed without merging**
