### PR TITLE
Prefer `Time` over `DateTime`

### PR DESCRIPTION
**Pull request by andyw8**

### CODE REVIEW

**Comment by mentero** [comment]
Someone was reading: https://gist.github.com/pixeltrix/e2298822dd89d854444b ;)

**Comment by bbatsov** [comment]
Generally it'd be better if you inlined the examples. Referring to external sources is a bad idea as they tend to change/disappear (and you force the reader to change context).

**Comment by bbatsov** [comment]
@andyw8 ping

**Comment by andyw8** [comment]
I'll come back to this when I have time.

**Pull request closed without merging**
