### PR TITLE
Add rules for hexadecimal, binary and decimal literal prefixes

### PR DESCRIPTION
**Pull request by tejasbubane**
Related to #578

@bbatsov suggested to add rule for hex numbers. I went ahead and added
one for binary as well.

### CODE REVIEW

**Comment by cremno** [comment]
There's also the rather pointless `0d`/`0D` prefix. I also think this can be condensed into one rule. Having 3 or even 4 very similar sections is kinda ugly.

**Comment by tejasbubane** [comment]
@cremno Thanks! Did not know about the `0d` prefix. I have added it but since it is pointless, not sure if we should keep it. 

And yes, the 4 very similar sections looked kinda ugly. I have combined them into a single section.

**Comment by cremno** [comment]
I think you've misunderstood. The following would make sense to me:

- use `0[bodx]` instead of `0[BODX]`
- use `0o` instead of `0` (like now but minus `0O` - it doesn't matter anyway if it's `00` or `0O`)

And maybe (@bbatsov?):

- don't use `0d`

**Comment by tejasbubane** [comment]
`0[bodx]` looks a little confusing to me.

**Comment by cremno** [comment]
My comment is just an example of how I would arrange the sections. I didn't want to propose anything in it as official wording or criticize yours.

**Comment by tejasbubane** [comment]
@cremno Yes, I understand. I just felt it a little confusing. Let's see what @bbatsov has to say.

**Comment by bbatsov** [comment]
Looks good to me.

**Pull request merged**
